### ISSUE TITLE
onSubmit typing issues

### ISSUE THREAD

**Issue by snavidi** [prezly/react-promise-modal#10]
I am using version 0.3.1 with TypeScript and React 18.

The documentation states:
"onSubmit — should be invoked when a modal is submitted/confirmed. Resolves to true if no arguments given. But you can pass any value as argument to defined resolve value. For obvious reason this value cannot be undefined.

The function returns a Promise that is resolved with an undefined if the modal was dismissed or true (or any value you provide) when it's submitted."

This is indeed how reactModal appears to work with our code; however my IDE (Jetbrains Webstorm) is warning that there are 2 issues:

**1. If passing a parameter into onSubmit, the IDE gives this TS error: "TS2554: Expected 0 arguments, but got 1"**

This example from the documentation (which I have adjusted very slightly) gives this error:

```ts
import reactModal from '@prezly/react-promise-modal';
import Modal from 'react-modal';
import React from "react";

const result = await reactModal(({ show, onSubmit, onDismiss }) => (
    // Use any modal implementation
    <Modal isOpen={show} onRequestClose={onDismiss}>
        OK?
        <button onClick={onDismiss}>Cancel</button>
        <button onClick={() => onSubmit('OK Clicked')}>OK</button>
    </Modal>
));
```

**2. My IDE is expecting a return type of True and gives a TS error when the return type is actually other than True**

The following code returns this error:
TS2345: Argument of type (result: MyCustomType) => void is not assignable to parameter of type (value: true) => void | PromiseLike<void>
Types of parameters result and value are incompatible.
Type true is not assignable to type "blah"

```ts
import reactModal from "@prezly/react-promise-modal";
import Modal from "react-modal";
import React from "react";


type MyCustomType = "blah";

function APICall(): Promise<MyCustomType> {
    return Promise.resolve("blah");
}

function InnerFunction({onClose, onSave}: { onClose(): void, onSave(myResult: MyCustomType): void }) {
    function onSubmit() {
        APICall().then(myResult => {onSave(myResult);})
    }
    
    return <button onClick={onSubmit}>Try me!</button>
}

function OuterFunction() {
    return reactModal(({show, onSubmit, onDismiss}) => {
        return (
            <Modal isOpen={show} onAfterOpen={() => {}} onRequestClose={() => {onDismiss()}}>
                <InnerFunction onClose={onDismiss} onSave={onSubmit}/>
            </Modal>
        )
    }).then((result: MyCustomType) => {
        console.log(result);

    })
}
```

**Comment by e1himself** [comment]
Hi Sonia! :wave: 

Thank you for reporting this. :raised_hands: 

Indeed, the code examples above do produce TS errors. I suspect this might be due to newer versions of Typescript having slightly different type inference logic. When the library was written, Typescript was v4, now it's at version 5.

The errors can be fixed by explicitly telling TypeScript which return type is expected from the modal promise:
(note the `<string>` generic type parameter being passed to `reactModal<...>()`):

```ts
import reactModal from '@prezly/react-promise-modal';
import Modal from 'react-modal';
import React from "react";

const result = await reactModal<string>(({ show, onSubmit, onDismiss }) => (
    // Use any modal implementation
    <Modal isOpen={show} onRequestClose={onDismiss}>
        OK?
        <button onClick={onDismiss}>Cancel</button>
        <button onClick={() => onSubmit('OK Clicked')}>OK</button>
    </Modal>
));
```

The second example can be fixed the same way:
(also note that the `then(...)` callback argument should be `MyCustomType | undefined` -- as undefined is used for dismissals).

```ts
import reactModal from "@prezly/react-promise-modal";
import Modal from "react-modal";
import React from "react";


type MyCustomType = "blah";

function APICall(): Promise<MyCustomType> {
    return Promise.resolve("blah");
}

function InnerFunction({onClose, onSave}: { onClose(): void, onSave(myResult: MyCustomType): void }) {
    function onSubmit() {
        APICall().then(myResult => {onSave(myResult);})
    }
    
    return <button onClick={onSubmit}>Try me!</button>
}

function OuterFunction() {
    // ---
    // Note `<MyCustomType>` below
    // --- 
    return reactModal<MyCustomType>(({show, onSubmit, onDismiss}) => {
        return (
            <Modal isOpen={show} onAfterOpen={() => {}} onRequestClose={() => {onDismiss()}}>
                <InnerFunction onClose={onDismiss} onSave={onSubmit}/>
            </Modal>
        )
    }).then((result: MyCustomType | undefined) => {
        // ---
        // Note `result: MyCustomType | undefined` above
        // --- 
        console.log(result);

    })
}
```

I hope this solves the issue. I also plan to update the README to not have errors in the examples :) 
Thanks!

**Comment by e1himself** [comment]
Also, do you use this library in production? How do you like it? (just curious :))

Internally in the company we're using a v2 of this approach, which fixes the issue of rendering out-of-the-app-context (see #2 and #4) and is based on React hooks. But we still haven't made time for publishing it publicly. 

The usage looks like this:

```tsx
const confirmation = usePromisedModal(({ show, onSubmit }) => (
    <Modal
        show={show}
        title="You have unsaved changes for this conflict. If you close this modal now, those changes will be lost."
        onDiscardChanges={() => onSubmit(true)}
        onKeepChanges={() => onSubmit(false)}
    />
));

async function handleClick() {
     const confirmed = await confirmation.invoke();
     if (confirmed) {
         document.location = '/';
     }
}

return (
   <div>
      <button onClick={handleClick}>Leave the page</button>
      {confirmation.modal}
   </div>
);
```

Are you interested in using the newer version? I'll try to make time to publish it as v2 of this package.

**Comment by e1himself** [comment]
> Internally in the company we're using a v2 of this approach, which fixes the issue of rendering out-of-the-app-context (see https://github.com/prezly/react-promise-modal/issues/2 and https://github.com/prezly/react-promise-modal/issues/4) and is based on React hooks. But we still haven't made time for publishing it publicly.

I've just published the second version of the implementation.
Please see the docs here: https://github.com/prezly/react-promise-modal
