### ISSUE TITLE
Suggestion: reuse the container div if its already avaiable in DOM

### ISSUE THREAD

**Issue by saswat3115** [prezly/react-promise-modal#3]
```js
let container = document.getElementById('custom-modal');
if (!container) {
    container = document.createElement('div');
    container.id = 'custom-modal';
    document.body.appendChild(container);
}
```

**Comment by saswat3115** [comment]
Sometimes when we use hot reloding (ex:- create-react-app) that time multiple instance of popup is creating in DOM. To avoid that you can add this peace of code

**Comment by e1himself** [comment]
Hi @saswat3115! 

Thanks for submitting this suggestion. 

I've been thinking about the best way to approach this. Just always overwriting the previous div doesn't sound like a great idea to me, as it will probably be very unexpected for most of the users. However, your use-case does make sense as well.

I've come to an idea, where we can pass optional `key` or `id` or `element` property into the `reactModal()` function to instruct it to reuse the existing div matching the given selector, if any.

What do you think about such solution?

**Comment by saswat3115** [comment]
```
let container = document.getElementById('custom-modal');
if (!container) {
    container = document.createElement('div');
    container.id = 'custom-modal';
    document.body.appendChild(container);
}
```

**Comment by e1himself** [comment]
This is no longer relevant. In the second version we no longer use the hacky approach of rendering outside of the React rendering root: 

https://github.com/prezly/react-promise-modal/tree/99118c3300490d94382ea7147bbbb58dffa90718
