### ISSUE TITLE
Uncaught Error: This component must be used inside a <RecoilRoot> component.

### ISSUE THREAD

**Issue by awe-sim** [prezly/react-promise-modal#4]
First of all, a really simple, yet incredibly useful utility this is! Kudos!

We use RecoilJS in my company app. I later introduced this ReactPromiseModal library as a way to simplify showing/hiding/reading dialog components. This works perfectly, until..... Until I read a Recoil value within the component passed to ReactPromiseModal.

I even tried changing the library code to not create a new DIV every time and instead re-use an existing DIV (that I have a useRef for) and still Recoil JS and ReactPromiseModal fail to play nicely with each other.

The offending line is this:
```
render(renderModal({ onSubmit, onDismiss, show: true }), container);
```

**Comment by e1himself** [comment]
Hi @awe-sim! 

Thanks for reporting the issue :+1: 

From what I understand, `RecoilRoot` provides some context to the wrapped components tree. If so, I believe this is a case of the library implementation limitation. It simplifies modal interactions but does that for a cost. The cost is that the modal is rendered outside of your React context, so you have no way to access values passed with context. 

Please read #2 for more details.

Is that it?

**Comment by awe-sim** [comment]
Thank you for taking out time to respond. The links you shared were very helpful in understanding both react promise modal, and react itself. :-)

I usually try using redux/recoil-free code inside react promise modal dialog, amd return an object upon which the caller can act upon.

Great library once again. Awesome job! :-)

**Comment by e1himself** [comment]
This issue has been properly addressed in version 2: 
https://github.com/prezly/react-promise-modal/tree/99118c3300490d94382ea7147bbbb58dffa90718
