### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by TheTakylo** [prezly/react-promise-modal#5]
is the project still relevant?

**Comment by e1himself** [comment]
It is! :)

And we actually use it with React 18 (without bumping the required version in the package.json).

However, we have the v2 implementation battle-tested internally, and ready soon to be published.

I'll release the React 18 version though.

**Comment by TheTakylo** [comment]
yes it is mainly to remove the depreciation warning.

ok great I made a PR just in case.

**Comment by e1himself** [comment]
Released as `0.3.0`
